[package]
name = "nes"
version = "0.1.0"
authors = ["bengdahl <bengdahl341@gmail.com>"]
edition = "2018"
# build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# structopt = { version = "0.3.4", default-features = false }
nes_core = { path = "../nes_core" }
sdl2 = "0.32.2"
