[package]
name = "nes_core"
version = "0.1.0"
authors = ["bengdahl <bengdahl341@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
derive_more = "0.99.2"
lazy_static = "1.4.0"